import { PUBLIC_ENV } from './env';

export const STELLAR_CONFIG = {
  NETWORK_PASSPHRASE: PUBLIC_ENV.NETWORK_PASSPHRASE,
  HORIZON_URL: PUBLIC_ENV.HORIZON_URL,
  RPC_URL: PUBLIC_ENV.RPC_URL,
  CONTRACT_ID: PUBLIC_ENV.CONTRACT_ID,
  ESCROWX_CONTRACT_ID: PUBLIC_ENV.ESCROWX_CONTRACT_ID,
  NETWORK: PUBLIC_ENV.NETWORK,
} as const;
